language: node_js
node_js:
- '0.12'
install: script/deps.sh
script: script/build.sh
after_success: script/deploy.sh
env:
  global:
    secure: IbCm8MLtVAXHrO2btJ4JTxm0APF3IM3qvRWX81ZcKTa6VnLAQUF5lnU7bd3kmU3GYvdqDhRoYfjo3hNJ0iJu+6cydoFjlCkh18sKK5YY5Ic17hLrrTWLSUzCs8I+lfUFQJ/vaBottBqDTAiSaW5+yNdCaNFTRAOEbXkfIvUiwDX8bhETVKw2rg2pXOHn7vOPgvE79w6ljURrasneqrL0CWpMn+OOjXkOPhnvI+/kfQhLKqaKbGP70B3GTas5bJ4NBViax/rSuIbLneh4UcMFTczkKGaMRHIgTNAKmqGTtWNol7qdGfrzoJL9UgcBlUiG3z53wM0aJe4FX8m0gmxLFwVaDjhJE+t0kbQ5U5JXboejzYdQjcWrzw6JPnva/Z2IIM3nTSLQLNuozgFUhxZZdRkMUnWWp7ZUr+7F18HhS08UBjmH2MAHgKG5tuxviaOQGauW2n6R+ZZfX/JO2pFCI1cQqEqr0gnHHR1Qwy9YU5tw7Nh/ZWeNIML+K6o/19XQp9qRjFp7g3wnJBkHEVOVsKqOGoT8D+icJW167KAfM+PTv1VwzQ/ZIghEvn5MoZIQj3Gmz7vCVqfhLdKMwSSxZJehKG4X0rJn9f+8zRyUYOrZjBL/DGV+IDD2c5B1ebc0TPen0OzacxBFaE2E611UR14GJQFweAsDZC4IecZG8v8=
